services:
  url-shortener:
    image: aherbert2/url-shortener:1.1.0
    ports:
      - "3000:3000"
    environment:
      AUTH_USER: admin
      AUTH_PASS: password
    volumes:
      - temp_url_shortener_var:/app/var

volumes:
  temp_url_shortener_var:
